### ISSUE TITLE
blueprint needs changing

### ISSUE THREAD

**Issue by smeierzubiesen** [benface/grav-plugin-freshdesk#2]
form 2.0 has not been around for a while, as a matter of fact we're on version 4.0, and gpm won't install freshdesk, due to this dependency

**Comment by benface** [comment]
@smeierzubiesen I merged your PR. Do I need to tag a new release?

**Comment by benface** [comment]
@smeierzubiesen Ok, just did. Can you tell me if you see the new version now? (Maybe clear caches to be sure.)

**Comment by smeierzubiesen** [comment]
after having cleared caches, still the same result
(simply deleting the contents of cache/gpm/ should be enough, surely??)
even when I ```./bin/grav cache``` the result is the same

**Comment by benface** [comment]
Hmm yeah I see that the latest version is 1.0.0 when I search for "freshdesk" [on here](https://getgrav.org/downloads/plugins). Haha I can't figure out how to publish a release on GPM...

**Comment by smeierzubiesen** [comment]
i've been looking for that answer myself a little while now lol

**Comment by benface** [comment]
Ok I asked in Discord and apparently there is nothing else to do but wait. They said "just check it after an hour".

**Comment by smeierzubiesen** [comment]
right ok, lol, i shall check again in a little while

**Comment by smeierzubiesen** [comment]
ok, good news, after again clearing the gpm caches, the new version 1.0.1 is now public and working
